### ISSUE TITLE
const word into index.js

### ISSUE THREAD

**Issue by jerethom** [atomantic/is-ua-webview#1]
Hello,

Can you pollify the index.js file please ?
(replace const -> var)

**Comment by atomantic** [comment]
Just curious, what version of Node are you running? `const` is supported in all versions of Node that are not considered security liabilities...

I don't mind making the change though

**Comment by atomantic** [comment]
pushed to npm @ 1.0.1

**Comment by jerethom** [comment]
I use Node v9.x but the problem does not come directly from node.

Your package must be used by a module that I use in an Angular project.

When I build the project for any type of platform (in this case IE), I have errors because IE 10 does not support the es6.

Thank you for the fix

**Comment by atomantic** [comment]
ah, gotcha--I hadn't even thought someone would use it in-browser :)

**Comment by agoxlea** [comment]
This seems to still be an issue. I am having a similar issue as @jerethom. The module that uses this as a dependency that I'm having issues with is ng2-semantic-ui.
