### ISSUE TITLE
Missing typings

### ISSUE THREAD

**Issue by Godefroy** [atomantic/is-ua-webview#7]
Hi,
Thank you for this package, it's useful :-)
Could you please publish a new version on npm with the typings? It seems that the published version doesn't have them.

**Comment by atomantic** [comment]
I don't use typescript but if you make a pull request, I'll accept it.

**Comment by Godefroy** [comment]
kotarella1110 already did it in MR https://github.com/atomantic/is-ua-webview/pull/3

It's just not published on npm yet (I guess, because I don't have index.d.ts in my node_modules).

**Comment by atomantic** [comment]
ah, pushed @1.0.2

**Comment by Godefroy** [comment]
Thanks!
